version: '3.3'
services:
  aop-time-tracker-app:
    container_name: aop-time-tracker-app
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      POSTGRES_SERVER: aop-time-tracker-db
      POSTGRES_PORT: 5432
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    depends_on:
      - aop-time-tracker-db

  aop-time-tracker-db:
    restart: always
    container_name: aop-time-tracker-db
    image: postgres:15.2-alpine
    environment:
      - POSTGRES_PASSWORD=password
