spring:
  application:
    name: aop-time-tracker
  output:
    ansi:
      enabled: ALWAYS
  profiles:
    group:
      default:
        - "dev"
      production:
        - "production"
    active: default
  sql:
    init:
      mode: always
  jpa:
    show-sql: false
    generate-ddl: true
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
  datasource:
    driver-class-name: org.postgresql.Driver
  mvc:
    format:
      date: yyyy-MM-dd
      date-time: yyyy-MM-dd'T'HH:mm:ss.SSSX
      time: HH:mm:ss

logging:
  level:
    com:
      example:
        aop: DEBUG
---

spring:
  config:
    activate:
      on-profile: dev
  datasource:
    url: jdbc:postgresql://localhost:5432/time_tracker
    username: postgres
    password: postgres

---

spring:
  config:
    activate:
      on-profile: production
  jpa:
    hibernate:
      ddl-auto: create-drop
  datasource:
    url: jdbc:postgresql://${POSTGRES_SERVER}:${POSTGRES_PORT}/${POSTGRES_DB}
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
